/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.QuanLyQuyenBUS;
import BUS.QuanLyTaiKhoanBUS;
import DTO.QuyenDTO;
import DTO.TaiKhoanDTO;
import GUI.MainPanel.Quyen;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author welcome
 */
public class SuaQuyenForm extends javax.swing.JFrame {

    private Quyen parentPanel;
    private String originalMaQuyen;
    private QuanLyQuyenBUS qlqBUS = new QuanLyQuyenBUS();
    
    /**
     * Creates new form SuaQuyenForm
     */
    public SuaQuyenForm(Quyen parent, String maQuyen, String tenQuyen, String chiTietQuyen) {
        initComponents();
        this.parentPanel = parent;
        this.originalMaQuyen = maQuyen;
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        // Thiết lập giá trị từ dữ liệu truyền vào
        txtMaQuyen.setText(maQuyen);
        txtTenQuyen.setText(tenQuyen);
        txtMaQuyen.setEditable(false); // Không cho phép sửa mã quyền
        
        // Thiết lập các checkbox dựa trên chuỗi chi tiết quyền
        setCheckboxes(chiTietQuyen);

        // Thêm vào constructor hoặc tạo phương thức setupButtonHandlers riêng
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtMaQuyen = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTenQuyen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        btnHuy = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setPreferredSize(new java.awt.Dimension(600, 400));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Cập nhật quyền");

        jLabel1.setText("Mã quyền:");

        jLabel2.setText("Tên quyền:");

        jLabel3.setText("Chi tiết quyền:");

        jCheckBox1.setText("Bán hàng");

        jCheckBox2.setText("Nhập hàng");

        jCheckBox3.setText("Sản phẩm");

        jCheckBox4.setText("Loại sản phẩm");

        jCheckBox5.setText("Tài Khoản");

        jCheckBox6.setText("Hóa đơn");

        jCheckBox7.setText("Khuyến mãi");

        jCheckBox8.setText("Nhân viên");

        jCheckBox9.setText("Khách hàng");

        jCheckBox10.setText("Nhà cung cấp");

        jCheckBox11.setText("Phiếu nhập");

        jCheckBox12.setText("Thống kê");

        jCheckBox13.setText("Phân quyền");

        btnHuy.setText("Hủy");

        btnSua.setText("Cập nhật");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1)
                            .addComponent(jCheckBox2)
                            .addComponent(jCheckBox3)
                            .addComponent(jCheckBox4)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnHuy)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox7)
                                    .addComponent(jCheckBox8)
                                    .addComponent(jCheckBox9)
                                    .addComponent(jCheckBox6)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(btnSua))))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtMaQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTenQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox11)
                    .addComponent(jCheckBox10)
                    .addComponent(jCheckBox5)
                    .addComponent(jCheckBox12)
                    .addComponent(jCheckBox13))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox6)
                    .addComponent(jCheckBox11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox7)
                    .addComponent(jCheckBox10))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox8)
                    .addComponent(jCheckBox5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox9)
                    .addComponent(jCheckBox12)
                    .addComponent(jCheckBox4))
                .addGap(18, 18, 18)
                .addComponent(jCheckBox13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHuy)
                    .addComponent(btnSua))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnSua;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtMaQuyen;
    private javax.swing.JTextField txtTenQuyen;
    // End of variables declaration//GEN-END:variables

    // Thiết lập trạng thái các checkbox dựa trên chuỗi chi tiết quyền
    private void setCheckboxes(String chiTietQuyen) {
        
        
        jCheckBox1.setSelected(chiTietQuyen.contains("qlBanHang"));
        jCheckBox2.setSelected(chiTietQuyen.contains("qlNhapHang"));
        jCheckBox3.setSelected(chiTietQuyen.contains("qlSanPham"));
        jCheckBox4.setSelected(chiTietQuyen.contains("qlLoaiSanPham"));
        jCheckBox5.setSelected(chiTietQuyen.contains("qlTaiKhoan"));
        jCheckBox6.setSelected(chiTietQuyen.contains("qlHoaDon"));
        jCheckBox7.setSelected(chiTietQuyen.contains("qlKhuyenMai"));
        jCheckBox8.setSelected(chiTietQuyen.contains("qlNhanVien"));
        jCheckBox9.setSelected(chiTietQuyen.contains("qlKhachHang"));
        jCheckBox10.setSelected(chiTietQuyen.contains("qlNhaCungCap"));
        jCheckBox11.setSelected(chiTietQuyen.contains("qlPhieuNhap"));
        jCheckBox12.setSelected(chiTietQuyen.contains("qlThongKe"));
        jCheckBox13.setSelected(chiTietQuyen.contains("qlQuyen"));
    }
    
    // Phương thức để tạo chuỗi chi tiết quyền từ các checkbox
    private String taoChiTietQuyen() {
        StringBuilder chiTiet = new StringBuilder();
        
        if (jCheckBox1.isSelected()) {
            chiTiet.append("qlBanHang ");
        }
        if (jCheckBox2.isSelected()) {
            chiTiet.append("qlNhapHang ");
        }
        if (jCheckBox3.isSelected()) {
            chiTiet.append("qlSanPham ");
        }
        if (jCheckBox4.isSelected()) {
            chiTiet.append("qlLoaiSanPham ");
        }
        if (jCheckBox5.isSelected()) {
            chiTiet.append("qlTaiKhoan ");
        }
        if (jCheckBox6.isSelected()) {
            chiTiet.append("qlHoaDon ");
        }
        if (jCheckBox7.isSelected()) {
            chiTiet.append("qlKhuyenMai ");
        }
        if (jCheckBox8.isSelected()) {
            chiTiet.append("qlNhanVien ");
        }
        if (jCheckBox9.isSelected()) {
            chiTiet.append("qlKhachHang ");
        }
        if (jCheckBox10.isSelected()) {
            chiTiet.append("qlNhaCungCap ");
        }
        if (jCheckBox11.isSelected()) {
            chiTiet.append("qlPhieuNhap ");
        }
        if (jCheckBox12.isSelected()) {
            chiTiet.append("qlThongKe ");
        }
        
        if (jCheckBox13.isSelected()) {
            chiTiet.append("qlQuyen ");
        }
        
        return chiTiet.toString().trim();
    }
    
    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {
        String tenQuyen = txtTenQuyen.getText().trim();
        
        if (tenQuyen.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tên quyền không được để trống!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            txtTenQuyen.requestFocus();
            return;
        }
        
        // Tạo chuỗi chi tiết quyền từ các checkbox
        String chiTietQuyen = taoChiTietQuyen();
        
        // Kiểm tra xem có quyền nào được chọn không
        if (chiTietQuyen.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn ít nhất một quyền!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Cập nhật quyền
        boolean ketQua = qlqBUS.update(originalMaQuyen, tenQuyen, chiTietQuyen);
        
        if (ketQua) {
            JOptionPane.showMessageDialog(this, "Cập nhật quyền thành công!");
            parentPanel.loadTable();
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Cập nhật quyền thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
    }
}
