/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.MainPanel;
import DTO.*;
import DAO.*;
import BUS.*;
import GUI.FormSuaChiTietKM;
import GUI.FormSuaKM;
import GUI.FormThemChiTietKM;
import GUI.FormThemKM;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import java.text.ParseException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.Stack;
import javax.swing.JOptionPane;


/**
 *
 * @author 0388153585
 */
public class KhuyenMaiGUI extends javax.swing.JPanel {
    private DefaultTableModel model3; //khuyen mai xai
    private DefaultTableModel model;  //chi tiet khuyen mai xai
    private DefaultTableModel model1; //san pham xai
    /**
     * Creates new form KhuyenMaiGUI
     */
    public KhuyenMaiGUI(){
        // TODO add your handling code here:
        Vector header= new Vector();
        header.add("STT");
        header.add("Mã KM");
        header.add("Tên KM");
        header.add("Ngày Bắt Đầu");
        header.add("Ngày Kết Thúc");
        header.add("Trạng Thái");
        model3 = new DefaultTableModel(header, 0);
        initComponents();
        txtTimKiem.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate(DocumentEvent e) { timKiem(); }
            public void removeUpdate(DocumentEvent e) { timKiem(); }
            public void changedUpdate(DocumentEvent e) { timKiem(); }
        });
        txtTimKiem1.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate(DocumentEvent e) { timKiem1(); }
            public void removeUpdate(DocumentEvent e) { timKiem1(); }
            public void changedUpdate(DocumentEvent e) { timKiem1(); }
        });
    }
    public KhuyenMaiGUI(DefaultTableModel model3) {
        initComponents();
        this.model3=model3;
        txtTimKiem.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate(DocumentEvent e) { timKiem(); }
            public void removeUpdate(DocumentEvent e) { timKiem(); }
            public void changedUpdate(DocumentEvent e) { timKiem(); }
        });
        txtTimKiem1.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate(DocumentEvent e) { timKiem1(); }
            public void removeUpdate(DocumentEvent e) { timKiem1(); }
            public void changedUpdate(DocumentEvent e) { timKiem1(); }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDSKM = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cboTimKiem = new javax.swing.JComboBox<>();
        txtTimKiem = new javax.swing.JTextField();
        btnLamMoi = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCTKM = new javax.swing.JTable();
        btnLamMoi1 = new javax.swing.JButton();
        btnThem1 = new javax.swing.JButton();
        btnSua1 = new javax.swing.JButton();
        btnXoa1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        cboTimKiem1 = new javax.swing.JComboBox<>();
        txtTimKiem1 = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1000, 600));

        jPanel1.setBackground(new java.awt.Color(25, 118, 210));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("KHUYẾN MÃI");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(416, 416, 416)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(16, 16, 16))
        );

        tblDSKM.setBackground(new java.awt.Color(255, 204, 102));
        tblDSKM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã KM", "Tên KM", "Ngày Bắt Đầu", "Ngày Kết Thúc", "Trạng Thái"
            }
        ));
        tblDSKM.setSelectionBackground(new java.awt.Color(255, 153, 0));
        tblDSKM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSKMMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDSKM);

        btnThem.setBackground(new java.awt.Color(255, 193, 7));
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(229, 57, 53));
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xoá");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(2, 136, 209));
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm"));

        cboTimKiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Mã khuyến mãi", "Tên khuyến mãi", "Ngày bắt đầu", "Ngày kết thúc" }));

        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cboTimKiem, 0, 128, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        btnLamMoi.setBackground(new java.awt.Color(67, 160, 71));
        btnLamMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnLamMoi.setText("Làm Mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Chi Tiết Khuyến Mãi");

        tblCTKM.setBackground(new java.awt.Color(153, 255, 153));
        tblCTKM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã KM", "Tên KM", "Tên SP", "Phần Trăm Giảm Giá"
            }
        ));
        tblCTKM.setSelectionBackground(new java.awt.Color(51, 204, 0));
        jScrollPane2.setViewportView(tblCTKM);

        btnLamMoi1.setBackground(new java.awt.Color(67, 160, 71));
        btnLamMoi1.setForeground(new java.awt.Color(255, 255, 255));
        btnLamMoi1.setText("Làm Mới");
        btnLamMoi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoi1ActionPerformed(evt);
            }
        });

        btnThem1.setBackground(new java.awt.Color(255, 204, 102));
        btnThem1.setForeground(new java.awt.Color(255, 255, 255));
        btnThem1.setText("Thêm");
        btnThem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem1ActionPerformed(evt);
            }
        });

        btnSua1.setBackground(new java.awt.Color(3, 169, 244));
        btnSua1.setForeground(new java.awt.Color(255, 255, 255));
        btnSua1.setText("Sửa");
        btnSua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua1ActionPerformed(evt);
            }
        });

        btnXoa1.setBackground(new java.awt.Color(229, 57, 53));
        btnXoa1.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa1.setText("Xoá");
        btnXoa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa1ActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm"));

        cboTimKiem1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Tên sản phẩm", "Phần trăm" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cboTimKiem1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTimKiem1, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboTimKiem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimKiem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLamMoi1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnThem1)
                        .addGap(33, 33, 33)
                        .addComponent(btnSua1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnXoa1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(609, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(221, 221, 221))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(378, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(38, 38, 38)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem1)
                    .addComponent(btnSua1)
                    .addComponent(btnXoa1))
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnLamMoi1)))
                .addContainerGap(136, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(45, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(134, 134, 134)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(251, 251, 251)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(btnLamMoi))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 922, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(btnSua))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnXoa, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnThem, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnLamMoi)))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblDSKMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSKMMouseClicked
        // TODO add your handling code here:
        int i = tblDSKM.getSelectedRow();
        if(i>=0){
            String maKM = (String) tblDSKM.getModel().getValueAt(i, 1);
            
            KhuyenMaiBUS bus= new KhuyenMaiBUS();
            ArrayList<ChiTietKMDTO> ds = bus.doc_CTKM(maKM);
            Vector header= new Vector();
            header.add("Mã KM");
            header.add("Tên KM");
            header.add("Tên SP");
            header.add("Phần Trăm Giảm Giá");
            
            model= new DefaultTableModel(header, 0);
            for(ChiTietKMDTO ct : ds){
                Vector row = new Vector();
                row.add(ct.maKM);
                row.add(ct.tenKM);
                row.add(ct.tenSP);
                row.add(ct.phanTram);
                model.addRow(row);
            }
            tblCTKM.setModel(model);
//            ChiTietKMGUI form= new ChiTietKMGUI(model, maKM);
//            form.tblCTKM.setModel(model);
//            form.setLocationRelativeTo(null);
//            form.setVisible(true);
        }
    }//GEN-LAST:event_tblDSKMMouseClicked

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        txtTimKiem.setText("");
        cboTimKiem.setSelectedItem("Tất cả");

        model3.setRowCount(0); // Xóa dữ liệu cũ
        KhuyenMaiBUS bus = new KhuyenMaiBUS();
        bus.doc_DSKM();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        int i = 1; 
        for(KhuyenMaiDTO km : KhuyenMaiBUS.dsKM){
            Vector row = new Vector();
            row.add(i++);
            row.add(km.maKM);
            row.add(km.tenKM);
            row.add(km.ngayBD);
            row.add(km.ngayKT);
            // So sánh ngày kết thúc với ngày hiện tại
            try {
                LocalDate ngayKT = LocalDate.parse(km.ngayKT, formatter);
                LocalDate today = LocalDate.now();
                if (ngayKT.isBefore(today)) {
                    row.add("Đã kết thúc");
                } else {
                    row.add("Chưa kết thúc");
                }
            } catch (DateTimeParseException e) {
                row.add("Không hợp lệ");
            }

            model3.addRow(row);
        }
        tblDSKM.setModel(model3);
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        FormThemKM kmgui = new FormThemKM(model3);
        String maMoi = sinhMaKhuyenMaiTuDong();
        kmgui.txtMaKM.setText(maMoi);
        kmgui.setVisible(true);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        int i = tblDSKM.getSelectedRow();
        if(i>=0){
            KhuyenMaiDTO km = new KhuyenMaiDTO();
            KhuyenMaiBUS bus = new KhuyenMaiBUS();
            km=KhuyenMaiBUS.dsKM.get(i);
            FormSuaKM form = new FormSuaKM(model3, bus, i);
            form.txtMaKM.setText(km.maKM);
            form.txtTenKM.setText(km.tenKM);
            
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            LocalDate start = LocalDate.parse(km.ngayBD, formatter);
            LocalDate end = LocalDate.parse(km.ngayKT, formatter);
            form.dateStart.setDate(java.sql.Date.valueOf(start));
            form.dateEnd.setDate(java.sql.Date.valueOf(end));
            form.setVisible(true);
            
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int i = tblDSKM.getSelectedRow();
        if(i>=0){
            KhuyenMaiDTO km = new KhuyenMaiDTO();
            KhuyenMaiBUS bus = new KhuyenMaiBUS();
            km= bus.dsKM.get(i);
            int xacnhan=JOptionPane.showConfirmDialog(
                    btnXoa, 
                    "Bạn có chắc muốn xoá chương trình khuyến mãi có mã là "+km.maKM,
                    "Bạn có chắc muốn xoá chương trình khuyến mãi này?",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE);
            if(xacnhan==JOptionPane.YES_OPTION){
                bus.xoaKhuyenMai(km.maKM);
                bus.dsKM.remove(i);
                model3.removeRow(i);
                tblDSKM.setModel(model3);
                JOptionPane.showMessageDialog(btnXoa, "Đã xoá nhà cung cấp thành công!");
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void btnLamMoi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoi1ActionPerformed
        // TODO add your handling code here:
        txtTimKiem1.setText("");
        cboTimKiem1.setSelectedItem("Tất cả");
        model.setRowCount(0); // Xóa dữ liệu cũ
        tblCTKM.setModel(model);
    }//GEN-LAST:event_btnLamMoi1ActionPerformed

    private void btnThem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem1ActionPerformed
        // TODO add your handling code here:
        int i = tblDSKM.getSelectedRow();
        if (i >= 0) {
            String maKM = tblDSKM.getModel().getValueAt(i, 1).toString();
            String tenKM = tblDSKM.getModel().getValueAt(i, 2).toString();
            
            Vector header= new Vector();
            header.add("STT");
            header.add("Mã sản phẩm");
            header.add("Tên sản phẩm");
            
            int l =1;
            model1= new DefaultTableModel(header, 0);
            SanPhamBUS bus = new SanPhamBUS();
            if(SanPhamBUS.dsSP==null) bus.docDS_SP();
            for(SanPhamDTO sp: SanPhamBUS.dsSP){
                Vector row = new Vector();
                row.add(l++);
                row.add(sp.MaSP);
                row.add(sp.TenSP);
                model1.addRow(row);
            }
            
            FormThemChiTietKM form = new FormThemChiTietKM(model);
            form.txtMaKM.setText(maKM);
            form.txtTenKM.setText(tenKM);
            form.tblChonSP.setModel(model1);
            form.setVisible(true);
        }
        
    }//GEN-LAST:event_btnThem1ActionPerformed

    private void btnSua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua1ActionPerformed
        // TODO add your handling code here:
        int i = tblCTKM.getSelectedRow();
        if(i>=0){
            String maKM=tblCTKM.getModel().getValueAt(i, 0).toString();
            String tenKM=tblCTKM.getModel().getValueAt(i, 1).toString();
            String tenSP=tblCTKM.getModel().getValueAt(i, 2).toString();
            String phanTram=tblCTKM.getModel().getValueAt(i, 3).toString();
            
            Vector header= new Vector();
            header.add("STT");
            header.add("Mã sản phẩm");
            header.add("Tên sản phẩm");
            
            int l =1;
            model1= new DefaultTableModel(header, 0);
            SanPhamBUS bus = new SanPhamBUS();
            if(SanPhamBUS.dsSP==null) bus.docDS_SP();
            for(SanPhamDTO sp: SanPhamBUS.dsSP){
                Vector row = new Vector();
                row.add(l++);
                row.add(sp.MaSP);
                row.add(sp.TenSP);
                model1.addRow(row);
            }
            
            FormSuaChiTietKM form = new FormSuaChiTietKM(model, i);
            form.txtMaKM.setText(maKM);
            form.txtTenKM.setText(tenKM);
            form.txtTenSP.setText(tenSP);
            form.txtPhanTram.setText(phanTram);
            form.tblChonSP.setModel(model1);
            form.setVisible(true);
        }
    }//GEN-LAST:event_btnSua1ActionPerformed

    private void btnXoa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa1ActionPerformed
        // TODO add your handling code here:
        int i = tblCTKM.getSelectedRow();
        if(i>=0){
            String maKM= tblCTKM.getModel().getValueAt(i, 0).toString();
            String tenSP=tblCTKM.getModel().getValueAt(i, 2).toString();
            SanPhamBUS bus = new SanPhamBUS();
            String maSP=bus.getMaSpByTen(tenSP);
            
            int xacnhan=JOptionPane.showConfirmDialog(
                    btnXoa1, 
                    "Bạn có chắc muốn xoá chi tiết khuyến mãi này ?",
                    "Bạn có chắc muốn xoá chi tiết khuyến mãi này ?",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE);
            if(xacnhan==JOptionPane.YES_OPTION){
                KhuyenMaiBUS buskm = new KhuyenMaiBUS();
                buskm.xoaChiTietKhuyenMai(maKM, maSP);
                model.removeRow(i);
                tblCTKM.setModel(model);
                JOptionPane.showMessageDialog(btnXoa, "Đã xoá nhà cung cấp thành công!");
            }   
        }
    }//GEN-LAST:event_btnXoa1ActionPerformed

    private void timKiem() {
        String tuKhoa = txtTimKiem.getText().trim().toLowerCase();
        String tieuChi = cboTimKiem.getSelectedItem().toString();

        model3.setRowCount(0); // Xóa dữ liệu cũ

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        int i = 1;

        KhuyenMaiBUS bus= new KhuyenMaiBUS();
        ArrayList<KhuyenMaiDTO> ds = bus.timKiemDSKM(tuKhoa, tieuChi);
        for (KhuyenMaiDTO km : ds) {
            Vector row = new Vector();
            row.add(i++);
            row.add(km.maKM);
            row.add(km.tenKM);
            row.add(km.ngayBD);
            row.add(km.ngayKT);

            try {
                LocalDate ngayKT = LocalDate.parse(km.ngayKT, formatter);
                if (ngayKT.isBefore(LocalDate.now())) {
                    row.add("Đã kết thúc");
                } else {
                    row.add("Chưa kết thúc");
                }
            } catch (DateTimeParseException e) {
                row.add("Không hợp lệ");
            }

            model3.addRow(row);
        }

        tblDSKM.setModel(model3);
    }
    public void timKiem1() {
        if(KhuyenMaiBUS.dsCTKM==null) return;
        String keyword = txtTimKiem1.getText().toLowerCase().trim();
        String tieuChi = cboTimKiem1.getSelectedItem().toString();

        model.setRowCount(0);

        for (ChiTietKMDTO ctkm : KhuyenMaiBUS.dsCTKM) {
            boolean match = false;
            
            // Lọc theo tiêu chí chọn trong combo box
            switch (tieuChi) {
                case "Tất cả":
                    match =
                        ctkm.tenSP.toLowerCase().contains(keyword) ||
                        ctkm.phanTram.toLowerCase().contains(keyword);   
                    break;

                case "Tên sản phẩm":
                    match = ctkm.tenSP.toLowerCase().contains(keyword);
                    break;

                case "Phần trăm":
                    match = ctkm.phanTram.toLowerCase().contains(keyword);
                    break;
            }
            
            if (match) {
                Vector row = new Vector();
                row.add(ctkm.maKM);
                row.add(ctkm.tenKM);
                row.add(ctkm.tenSP);
                row.add(ctkm.phanTram);
                model.addRow(row);
            }
        }
        tblCTKM.setModel(model);
    }
    private String sinhMaKhuyenMaiTuDong() {
        int max = 0;
        for (int i = 0; i < tblDSKM.getRowCount(); i++) {
            String ma = tblDSKM.getValueAt(i, 1).toString(); // Cột 1 là Mã KM
            if (ma.startsWith("KM")) {
                try {
                    int so = Integer.parseInt(ma.substring(2));
                    if (so > max) {
                        max = so;
                    }
                } catch (NumberFormatException e) {
                    // Bỏ qua mã không hợp lệ
                }
            }
        }
        return "KM" + (max + 1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnLamMoi1;
    public javax.swing.JButton btnSua;
    private javax.swing.JButton btnSua1;
    public javax.swing.JButton btnThem;
    private javax.swing.JButton btnThem1;
    public javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoa1;
    public javax.swing.JComboBox<String> cboTimKiem;
    private javax.swing.JComboBox<String> cboTimKiem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable tblCTKM;
    public javax.swing.JTable tblDSKM;
    public javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtTimKiem1;
    // End of variables declaration//GEN-END:variables
}
