/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.MainPanel;

import javax.swing.table.DefaultTableModel;
import DTO.NhaCungCapDTO;
import DAO.NhaCungCapDAO;
import BUS.NhaCungCapBUS;
import GUI.FormSuaNhaCungCap;
import GUI.FormThemNCC;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.util.ArrayList;
import java.util.Stack;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.*;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.DateUtil;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author 0388153585
 */
public class QuanLyNhaCungCapForm extends javax.swing.JPanel {
    private DefaultTableModel model;
    /**
     * Creates new form NhaCungCapGUI
     */
    public QuanLyNhaCungCapForm() {
        initComponents();
        Vector header= new Vector();
        header.add("STT");
        header.add("Mã NCC");
        header.add("Tên NCC");
        header.add("Địa chỉ");
        header.add("Số điện thoại");
        model = new DefaultTableModel(header, 0);
        int i=1;
        NhaCungCapBUS bus = new NhaCungCapBUS();
        if(NhaCungCapBUS.dsNCC==null) bus.docDS_NCC();
        for(NhaCungCapDTO ncc: NhaCungCapBUS.dsNCC){
            Vector row = new Vector();
            row.add(i++);
            row.add(ncc.maNCC);
            row.add(ncc.tenNCC);
            row.add(ncc.diaChi);
            row.add(ncc.soDT);
            model.addRow(row);
        }
        tblDS_NCC.setModel(model);
        txtTimKiem.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate(DocumentEvent e) {
                timKiemTuDong();
            }

            public void removeUpdate(DocumentEvent e) {
                timKiemTuDong();
            }

            public void changedUpdate(DocumentEvent e) {
                timKiemTuDong();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDS_NCC = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXuatEX = new javax.swing.JButton();
        btnNhapEX = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        cboTimKiem = new javax.swing.JComboBox<>();
        txtTimKiem = new javax.swing.JTextField();
        btnLamMoi = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1000, 600));

        tblDS_NCC.setBackground(new java.awt.Color(255, 204, 102));
        tblDS_NCC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã NCC", "Tên NCC", "Địa chỉ", "Số điện thoại"
            }
        ));
        tblDS_NCC.setSelectionBackground(new java.awt.Color(255, 153, 0));
        tblDS_NCC.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tblDS_NCC);

        btnThem.setBackground(new java.awt.Color(76, 175, 80));
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("➕ Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(244, 67, 54));
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("❌ Xoá");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(33, 150, 243));
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setText("⚙️️ Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXuatEX.setBackground(new java.awt.Color(255, 193, 7));
        btnXuatEX.setForeground(new java.awt.Color(255, 255, 255));
        btnXuatEX.setText("📤 Xuất Excel");
        btnXuatEX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatEXActionPerformed(evt);
            }
        });

        btnNhapEX.setBackground(new java.awt.Color(3, 169, 244));
        btnNhapEX.setForeground(new java.awt.Color(255, 255, 255));
        btnNhapEX.setText(" 📥 Nhập Excel");
        btnNhapEX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapEXActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm"));

        cboTimKiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Mã NCC", "Tên NCC", "Địa chỉ", "Số điện thoại" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cboTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        btnLamMoi.setBackground(new java.awt.Color(67, 160, 71));
        btnLamMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnLamMoi.setText("🔄 Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(25, 118, 210));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NHÀ CUNG CẤP");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(393, 393, 393))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(329, 329, 329)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnThem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXuatEX)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNhapEX))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLamMoi)))
                .addContainerGap(217, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(btnSua)
                    .addComponent(btnXuatEX)
                    .addComponent(btnNhapEX))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnLamMoi)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(278, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        // Lấy model hiện tại từ bảng
        model = (DefaultTableModel) tblDS_NCC.getModel();

        // Truyền model sang form thêm NCC
        FormThemNCC form = new FormThemNCC(model);
        form.setVisible(true);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        txtTimKiem.setText("");                       // Xóa ô tìm kiếm
        cboTimKiem.setSelectedItem("Tất cả");         // Reset combobox

        DefaultTableModel model = new DefaultTableModel();
        Vector header = new Vector();
        header.add("STT");
        header.add("Mã NCC");
        header.add("Tên NCC");
        header.add("Địa chỉ");
        header.add("Số ĐT");
        model.setColumnIdentifiers(header);

        int i = 1;
        for (NhaCungCapDTO ncc : NhaCungCapBUS.dsNCC) {
            Vector row = new Vector();
            row.add(i++);
            row.add(ncc.getMaNCC());
            row.add(ncc.getTenNCC());
            row.add(ncc.getDiaChi());
            row.add(ncc.getSoDT());
            model.addRow(row);
        }

        tblDS_NCC.setModel(model); // cập nhật bảng
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int i= tblDS_NCC.getSelectedRow();
        if(i>=0){
            NhaCungCapDTO ncc= new NhaCungCapDTO();
            NhaCungCapBUS bus= new NhaCungCapBUS();
            ncc=bus.dsNCC.get(i);
            int xacnhan=JOptionPane.showConfirmDialog(
                    btnXoa, 
                    "Bạn có chắc muốn xoá nhà cung cấp có mã là "+ncc.maNCC,
                    "Bạn có chắc muốn xoá nhà cung cấp này?",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE);
            if(xacnhan==JOptionPane.YES_OPTION){
                model= (DefaultTableModel) tblDS_NCC.getModel();
                bus.xoaNCC(ncc.maNCC);
                bus.dsNCC.remove(i);
                model.removeRow(i);
                tblDS_NCC.setModel(model);
                JOptionPane.showMessageDialog(btnXoa, "Đã xoá nhà cung cấp thành công!");
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        int i= tblDS_NCC.getSelectedRow();
        if(i>=0){
            NhaCungCapDTO ncc= new NhaCungCapDTO();
            NhaCungCapBUS bus= new NhaCungCapBUS();
            ncc=bus.dsNCC.get(i);
            model = (DefaultTableModel) tblDS_NCC.getModel();
            FormSuaNhaCungCap form= new FormSuaNhaCungCap(model,bus,i);
            form.txtMaNCC.setText(ncc.maNCC);
            form.txtTenNCC.setText(ncc.tenNCC);
            form.txtDiaChi.setText(ncc.diaChi);
            form.txtSDT.setText(ncc.soDT);
            form.setVisible(true);
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXuatEXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatEXActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Chọn nơi lưu file Excel");

        int userSelection = fileChooser.showSaveDialog(this);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();

            // Đảm bảo file có đuôi .xlsx
            String filePath = fileToSave.getAbsolutePath();
            if (!filePath.endsWith(".xlsx")) {
                filePath += ".xlsx";
            }

            try (XSSFWorkbook workbook = new XSSFWorkbook()) {
                XSSFSheet sheet = workbook.createSheet("Danh sách NCC");

                DefaultTableModel model = (DefaultTableModel) tblDS_NCC.getModel();

                // Ghi header (tên cột)
                Row header = sheet.createRow(0);
                for (int i = 0; i < model.getColumnCount(); i++) {
                    Cell cell = header.createCell(i);
                    cell.setCellValue(model.getColumnName(i));
                }

                // Ghi dữ liệu từng dòng
                for (int row = 0; row < model.getRowCount(); row++) {
                    Row excelRow = sheet.createRow(row + 1);
                    for (int col = 0; col < model.getColumnCount(); col++) {
                        Cell cell = excelRow.createCell(col);
                        Object value = model.getValueAt(row, col);
                        cell.setCellValue(value != null ? value.toString() : "");
                    }
                }

                // Ghi ra file
                try (FileOutputStream fos = new FileOutputStream(filePath)) {
                    workbook.write(fos);
                }

                JOptionPane.showMessageDialog(this, "Xuất Excel thành công:\n" + filePath);

            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Lỗi khi xuất Excel: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnXuatEXActionPerformed

    private void btnNhapEXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapEXActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();

            try (FileInputStream fis = new FileInputStream(selectedFile);
                 XSSFWorkbook workbook = new XSSFWorkbook(fis)) {

                XSSFSheet sheet = workbook.getSheetAt(0); // lấy sheet đầu tiên
                DefaultTableModel model = (DefaultTableModel) tblDS_NCC.getModel();
                model.setRowCount(0); // xóa dữ liệu cũ

                boolean isFirstRow = true;
                for (Row row : sheet) {
                    if (isFirstRow) {
                        isFirstRow = false; // bỏ qua dòng tiêu đề
                        continue;
                    }

                    Vector<Object> rowData = new Vector<>();
                    for (int cn = 0; cn < 5; cn++) { // 5 cột: STT, MãNCC, TênNCC, Địa chỉ, SĐT
                        Cell cell = row.getCell(cn, Row.MissingCellPolicy.CREATE_NULL_AS_BLANK);

                        switch (cell.getCellType()) {
                            case STRING:
                                rowData.add(cell.getStringCellValue());
                                break;
                            case NUMERIC:
                                if (DateUtil.isCellDateFormatted(cell)) {
                                    rowData.add(cell.getDateCellValue().toString());
                                } else {
                                    rowData.add((long) cell.getNumericCellValue()); // xử lý số nguyên
                                }
                                break;
                            case BOOLEAN:
                                rowData.add(cell.getBooleanCellValue());
                                break;
                            case BLANK:
                                rowData.add("");
                                break;
                            default:
                                rowData.add(cell.toString());
                        }
                    }

                    model.addRow(rowData);
                }

                JOptionPane.showMessageDialog(this, "Đã nhập Excel thành công!");

            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Lỗi khi đọc file Excel: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnNhapEXActionPerformed
    
    private void timKiemTuDong() {
        String tieuChi = cboTimKiem.getSelectedItem().toString();
        String tuKhoa = txtTimKiem.getText().trim();

        NhaCungCapBUS bus = new NhaCungCapBUS();
        ArrayList<NhaCungCapDTO> ketQua = bus.timKiem(tieuChi, tuKhoa);

        DefaultTableModel model = new DefaultTableModel();
        Vector header = new Vector();
        header.add("STT");
        header.add("Mã NCC");
        header.add("Tên NCC");
        header.add("Địa chỉ");
        header.add("Số ĐT");
        model.setColumnIdentifiers(header);

        int i = 1;
        for (NhaCungCapDTO ncc : ketQua) {
            Vector row = new Vector();
            row.add(i++);
            row.add(ncc.getMaNCC());
            row.add(ncc.getTenNCC());
            row.add(ncc.getDiaChi());
            row.add(ncc.getSoDT());
            model.addRow(row);
        }

        tblDS_NCC.setModel(model);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnLamMoi;
    public javax.swing.JButton btnNhapEX;
    public javax.swing.JButton btnSua;
    public javax.swing.JButton btnThem;
    public javax.swing.JButton btnXoa;
    public javax.swing.JButton btnXuatEX;
    public javax.swing.JComboBox<String> cboTimKiem;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tblDS_NCC;
    public javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
