/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package GUI.MainPanel;


import BUS.SanPhammBUS;
import DTO.SanPhammDTO;
import GUI.FormSuaSP;
import GUI.FormThemSP;
import java.awt.Component;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import java.sql.SQLException;
/**
 *
 * @author datti
 */
public class SanPhamGUI extends javax.swing.JPanel {

    /**
     * Creates new form SanPhamGUI
     */
    

    public SanPhamGUI() {
        initComponents();
        loadData();
        txtTimKiem.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                timKiemSanPham();
            }
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                timKiemSanPham();
            }
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                timKiemSanPham();
            }
        });

        cboTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                timKiemSanPham();
            }
        });        
    }

    // Cuối class SanPhamGUI, ngay trước dấu đóng class }

    private void loadData() {
        SanPhammBUS bus = new SanPhammBUS(DBConnect.Connector.getConnection()); // Sử dụng connection từ Connector
        ArrayList<SanPhammDTO> ds = bus.layDSSanPham();

        DefaultTableModel model = (DefaultTableModel) tblDS_SP.getModel();
        model.setRowCount(0);

        for (SanPhammDTO sp : ds) {
            model.addRow(new Object[]{
                sp.getMaSP(),
                sp.getTenSP(),
                sp.getSoLuong(),
                sp.getDonGia(),
                sp.getDonVi(),
                sp.getMaLoai(),
                sp.getHinhAnh(),
                sp.getTenLoai()
            });
        }

//        tblDS_SP.getColumnModel().getColumn(6).setCellRenderer(new ImageRenderer());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnThem = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtTenSP = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        txtmaloai = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        txtdongia = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDS_SP = new javax.swing.JTable();
        btnsuasp = new javax.swing.JButton();
        bntlammoi = new javax.swing.JButton();
        bntxoa = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cboTimKiem = new javax.swing.JComboBox<>();
        txtTimKiem = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        btnThem.setBackground(new java.awt.Color(2, 136, 209));
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("THÊM");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("SẢN PHẨM"));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tên Sản Phẩm"));

        txtTenSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenSPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTenSP, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Tên Loại"));

        txtmaloai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmaloaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtmaloai)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtmaloai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Đơn Giá"));

        txtdongia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdongiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtdongia)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(txtdongia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tblDS_SP.setBackground(new java.awt.Color(153, 255, 153));
        tblDS_SP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "MÃ SP", "TÊN SP", "SỐ LƯỢNG", "ĐƠN GIÁ", "ĐƠN VỊ", "MÃ LOẠI", "URL ẢNH", "TÊN LOẠI"
            }
        ));
        tblDS_SP.setSelectionBackground(new java.awt.Color(51, 204, 0));
        tblDS_SP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDS_SPMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDS_SP);

        btnsuasp.setBackground(new java.awt.Color(255, 193, 7));
        btnsuasp.setForeground(new java.awt.Color(255, 255, 255));
        btnsuasp.setText("SỬA");
        btnsuasp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaspActionPerformed(evt);
            }
        });

        bntlammoi.setBackground(new java.awt.Color(67, 160, 71));
        bntlammoi.setForeground(new java.awt.Color(255, 255, 255));
        bntlammoi.setText("Làm Mới");
        bntlammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntlammoiActionPerformed(evt);
            }
        });

        bntxoa.setBackground(new java.awt.Color(229, 57, 53));
        bntxoa.setForeground(new java.awt.Color(255, 255, 255));
        bntxoa.setText("XÓA");
        bntxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntxoaActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm"));

        cboTimKiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Mã SP", "Tên SP", "Đơn Vị", "Mã Loại", " " }));

        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cboTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(25, 118, 210));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SẢN PHẨM");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(365, 365, 365)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(261, 261, 261)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(btnThem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnsuasp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bntxoa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(197, 197, 197)
                                .addComponent(bntlammoi)))
                        .addGap(0, 135, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem)
                            .addComponent(btnsuasp)
                            .addComponent(bntlammoi)
                            .addComponent(bntxoa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblDS_SPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDS_SPMouseClicked
        // TODO add your handling code here:
        int i= tblDS_SP.getSelectedRow();
        if(i>=0){
            String hinhAnh= (String )tblDS_SP.getModel().getValueAt(i, 6);
            ImageIcon icon = new ImageIcon(hinhAnh); // đường dẫn ảnh
            Image img = icon.getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH);
            jLabel2.setIcon(new ImageIcon(img));
            String TenSanPham= (String )tblDS_SP.getModel().getValueAt(i, 1);
            txtTenSP.setText(TenSanPham);
            String TenLoai= (String )tblDS_SP.getModel().getValueAt(i, 7);
            txtmaloai.setText(TenLoai);
            Double DonGia = (Double) tblDS_SP.getModel().getValueAt(i, 3);
            txtdongia.setText(String.valueOf(DonGia));
        }
    }//GEN-LAST:event_tblDS_SPMouseClicked

    private void txtTenSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenSPActionPerformed

    private void txtmaloaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmaloaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmaloaiActionPerformed

    private void txtdongiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdongiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdongiaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        FormThemSP frm = new FormThemSP();
        frm.setLocationRelativeTo(null); // căn giữa
        frm.setVisible(true);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnsuaspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaspActionPerformed
        // TODO add your handling code here:
        
        
            int selectedRow = tblDS_SP.getSelectedRow();
            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(null, "Vui lòng chọn sản phẩm cần sửa.");
                return;
            }

            // Lấy dữ liệu từ dòng được chọn
            String maSP = tblDS_SP.getValueAt(selectedRow, 0).toString();
            String tenSP = tblDS_SP.getValueAt(selectedRow, 1).toString();
            String soLuong = tblDS_SP.getValueAt(selectedRow, 2).toString();
            String donGia = tblDS_SP.getValueAt(selectedRow, 3).toString();
            String donVi = tblDS_SP.getValueAt(selectedRow, 4).toString();
            String maLoai = tblDS_SP.getValueAt(selectedRow, 5).toString();
            String hinhAnh = tblDS_SP.getValueAt(selectedRow, 6).toString();

            // Mở form sửa và truyền dữ liệu vào
            FormSuaSP formSua = new FormSuaSP();
            formSua.setFields(maSP, tenSP, donGia, donVi, maLoai, hinhAnh);
            formSua.setVisible(true);

            // Khi form sửa đóng lại, reload bảng (nếu cập nhật thành công)
            formSua.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosed(java.awt.event.WindowEvent e) {
                    loadData(); // gọi lại để load bảng mới
                }
            });
        
    }//GEN-LAST:event_btnsuaspActionPerformed

    private void bntlammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntlammoiActionPerformed
        // TODO add your handling code here:
        loadData();
    }//GEN-LAST:event_bntlammoiActionPerformed

    private void bntxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntxoaActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblDS_SP.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng để xóa!");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa sản phẩm này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        String maSP = tblDS_SP.getValueAt(selectedRow, 0).toString();
//        SanPhamBUS bus = new SanPhamBUS(DBConnect.Connector.getConnection());
//        boolean result = bus.deleteSanPham(maSP);
//        if (result) {
//            JOptionPane.showMessageDialog(this, "Xóa thành công!");
//            loadData();  // Cập nhật lại bảng
//        } else {
//            JOptionPane.showMessageDialog(this, "Xóa thất bại. Kiểm tra ràng buộc dữ liệu.");
//        }
        
        try {
            SanPhammBUS bus = new SanPhammBUS(DBConnect.Connector.getConnection());
            boolean result = bus.deleteSanPham(maSP);
            if (result) {
                JOptionPane.showMessageDialog(this, "Xóa thành công!");
                loadData();
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thất bại!");
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi cơ sở dữ liệu: " + e.getMessage());
        }
      
    }//GEN-LAST:event_bntxoaActionPerformed

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtTimKiemActionPerformed
    private void timKiemSanPham() {
        String tuKhoa = txtTimKiem.getText().trim().toLowerCase();
        String tieuChi = (String) cboTimKiem.getSelectedItem();

        SanPhammBUS bus = new SanPhammBUS(DBConnect.Connector.getConnection());
        ArrayList<SanPhammDTO> danhSach = bus.layDSSanPham(); // Lấy toàn bộ danh sách

        ArrayList<SanPhammDTO> ketQua = new ArrayList<>();

        for (SanPhammDTO sp : danhSach) {
            switch (tieuChi) {
                case "Tất cả":
                    if (sp.getMaSP().toLowerCase().contains(tuKhoa) ||
                        sp.getTenSP().toLowerCase().contains(tuKhoa) ||
                        sp.getDonVi().toLowerCase().contains(tuKhoa) ||
                        sp.getMaLoai().toLowerCase().contains(tuKhoa)) {
                        ketQua.add(sp);
                    }
                    break;
                case "Mã SP":
                    if (sp.getMaSP().toLowerCase().contains(tuKhoa)) {
                        ketQua.add(sp);
                    }
                    break;
                case "Tên SP":
                    if (sp.getTenSP().toLowerCase().contains(tuKhoa)) {
                        ketQua.add(sp);
                    }
                    break;
                case "Đơn Vị":
                    if (sp.getDonVi().toLowerCase().contains(tuKhoa)) {
                        ketQua.add(sp);
                    }
                    break;
                case "Mã Loại":
                    if (sp.getMaLoai().toLowerCase().contains(tuKhoa)) {
                        ketQua.add(sp);
                    }
                    break;
            }
        }

        DefaultTableModel model = (DefaultTableModel) tblDS_SP.getModel();
        model.setRowCount(0);

        for (SanPhammDTO sp : ketQua) {
            model.addRow(new Object[]{
                sp.getMaSP(),
                sp.getTenSP(),
                sp.getSoLuong(),
                sp.getDonGia(),
                sp.getDonVi(),
                sp.getMaLoai(),
                sp.getHinhAnh(),
                sp.getTenLoai()
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntlammoi;
    private javax.swing.JButton bntxoa;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnsuasp;
    public javax.swing.JComboBox<String> cboTimKiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDS_SP;
    private javax.swing.JTextField txtTenSP;
    public javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtdongia;
    private javax.swing.JTextField txtmaloai;
    // End of variables declaration//GEN-END:variables
}
